---
- name: Install NGINX and Configure Firewall
  hosts: azure_vms
  gather_facts: false

  tasks:
    - name: Update package lists (apt-get update)
      become: yes
      apt:
        update_cache: yes
      register: apt_update_result

    - name: Check if package lists were updated
      debug:
        var: apt_update_result

    - name: Install NGINX
      become: yes
      apt:
        name: nginx
        state: present
    
    - name: Ensure NGINX service is started and enabled
      become: yes
      systemd:
        name: nginx
        state: started
        enabled: yes
        
    - name: Create NGINX reverse proxy configuration
      become: yes
      template:
        src: nginx_reverse_proxy.conf.j2
        dest: /etc/nginx/sites-available/reverse_proxy.conf
      notify: Reload NGINX
      
    - name: Enable NGINX reverse proxy configuration
      become: yes
      file:
        src: /etc/nginx/sites-available/reverse_proxy.conf
        dest: /etc/nginx/sites-enabled/reverse_proxy.conf
        state: link
      notify: Reload NGINX

  handlers:
    - name: Reload NGINX
      become: yes
      service:
        name: nginx
        state: reloaded
